server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:auth_server}?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:bass}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  management:
    endpoints:
      web:
        exposure:
          include: health,info,refresh
    endpoint:
      health:
        show-details: always

  logging:
    level:
      dev.edgeahz.ec.sports.authsrver: DEBUG
      org.springdoc: DEBUG
      org.springframework.web: INFO
      org.springframework.security: INFO

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    packages-to-scan: dev.edgeahz.ec.sports.authserver.api.rest

oauth:
  client:
    defaults:
      grant-types:
        - authorization_code
      response-types:
        - code
      token-endpoint-auth-method: client_secret_basic
      id-token-signed-response-alg: RS256
      access-token-validity-seconds: 3600
      refresh-token-validity-seconds: 86400
